### PR TITLE
Initial homepage design for the new crunch.io website

### PR DESCRIPTION
**Pull request by nataliasb**
https://www.pivotaltracker.com/story/show/154681275

### CODE REVIEW

**Comment by nealrichardson** [comment]
If I check out this branch and run `hugo serve`, I see our current site. What am I missing?

**Comment by enriquecastl** [comment]
@nealrichardson: @nataliasb is working in the templates in the new-site folder. We want to implement the entire layout and then adapt it to hugo which should be straightforward. In this way we have the freedom to move fast without having to deal with the old structure and styles from the old site and we can also deliver the new site in several tickets.

**Comment by nealrichardson** [comment]
That's fine, so how do I serve this so I can see?

**Comment by enriquecastl** [comment]
`cd new-site`
`npm install`
`yarn run node-sass source/scss/ -o static/css/`
`open index.html`

**Comment by nataliasb** [comment]
Once you npm install 

`npm run build:scss`

**Pull request merged**
